---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
  options:
    config-data:
      ignore: ".travis.yml"
platforms:
  - name: molecule-instance
    zone: europe-west1-b
    machine_type: f1-micro
    image: ubuntu-1604-xenial
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
